### ISSUE TITLE
Clear rating when selecting the same rating

### ISSUE THREAD

**Issue by aurelhubert** [ome450901/SimpleRatingBar#10]
Hi,

Thanks for the library, simple but exactly what we need for a rating bar. One small question: is it normal that the rating is cleaned when the user select twice the same rating? I think this behavior is quite a bit strange.
In the `onTouchEvent(MotionEvent event)` method:

```java
if (mPreviousRating == rating) {
    clearRating();
} else {
    setRating(view.getId());
}
```
I think the user should decide about this behavior.

**Comment by ome450901** [comment]
Hello, 

Thanks for your response!
I'll add a method to let user decide whether clearRating when select twice the same rating.
