### ISSUE TITLE
Set SimpleRatingBar lockable

### ISSUE THREAD

**Issue by aurelhubert** [ome450901/SimpleRatingBar#11]
Hi again,

Last suggestion, you should add a lockable state to just diplay the rating bar & disable the touch event. To do it, just add a parameter:

```java
private boolean isLocked = false;
``` 
In the onTouchEvent:
```java
@Override
public boolean onTouchEvent(MotionEvent event) {
        
        if (isLocked) {
            return true;
        }
        ...
}
```
And the getter/setter:
```java
public boolean isLocked() {
	return isLocked;
}
	
public void setLocked(boolean locked) {
	isLocked = locked;
}
```
Thanks! 👍

**Comment by ome450901** [comment]
Hello, 
I just added this feature in newest release(v1.2) hours ago XDD
but still thanks for your suggestion!
