### ISSUE TITLE
when it use in recyclerview have some problem

### ISSUE THREAD

**Issue by senlsy** [ome450901/SimpleRatingBar#15]
change PartialView.class resolve 
public void setFilledDrawable(Drawable drawable) {
         //new : drawable.getConstantState().newDrawable()
        ClipDrawable clipDrawable = new ClipDrawable(drawable.getConstantState().newDrawable(), Gravity.LEFT, ClipDrawable.HORIZONTAL);
        mFilledView.setImageDrawable(clipDrawable);
    }

    public void setEmptyDrawable(Drawable drawable) {
         //new : drawable.getConstantState().newDrawable()
        ClipDrawable clipDrawable = new ClipDrawable(drawable.getConstantState().newDrawable(), Gravity.RIGHT, ClipDrawable.HORIZONTAL);
        mEmptyView.setImageDrawable(clipDrawable);
    }

**Comment by gsanguinetti** [comment]
I have some problems too when I use it inside a recycler view.

**Comment by ome450901** [comment]
Hello @senlsy ,
Oh my gosh, I'm too late to see your response!!!
could you tell me why this bug happened? I have find a way to resolve this problem several weeks. orz

Thank you very much for providing this solution!
