### ISSUE TITLE
Half rating by touch event not working

### ISSUE THREAD

**Issue by darwinfrancis** [ome450901/SimpleRatingBar#19]
I am not able to choose half rating (ex:  2.5,3.5 etc) using touch events, but using java code it works fine.
The default android rating bar provides this feature.
![capture](https://user-images.githubusercontent.com/6102490/28857383-d2631052-7766-11e7-8a3e-ff682a4a2fb7.JPG)

**Comment by ome450901** [comment]
Hello @darwinfrancis , 
There is still have some bugs in this feature, so I haven't put it into the library.
But I'm working on it, thanks for your response!

**Comment by darwinfrancis** [comment]
Okey.
Can you give me approximate release date for the library with this feature.

**Comment by ome450901** [comment]
I have done this feature, but animation is not very smooth for Scale and Rotation RatingBar (it's okay in BaseRatingBar) currently.
I haven't found a better way to solve it. but you still can test this feature in SNAPSHOT version:

```gradle
compile 'com.github.ome450901:SimpleRatingBar:develop-SNAPSHOT'
```

Thanks.

**Comment by darwinfrancis** [comment]
Thank you, I will give u feedback once I got integrated in app.
