### ISSUE TITLE
stars disappear bug

### ISSUE THREAD

**Issue by AmineNac** [ome450901/SimpleRatingBar#23]
the stars disappearing bug remains even in the latest version

**Comment by ome450901** [comment]
Hello @AmineNac , 
Could you explain some detail about your situation or how to reproduce?
Thank you very much!

**Comment by k354250377** [comment]
我这边也是 在最新的版本星星也不见了

**Comment by ome450901** [comment]
Hello @k354250377 , 
可以請你描述一下是在什麼情況下星星會不見嗎？
謝謝！

**Comment by Sirelon** [comment]
@AmineNac I can confirm that in version 1.3 it was fixed.

**Comment by Callmebosswang** [comment]
选择了星星以后,跳转到新的Activity, 返回时选中的星星不见了, 选择又可以出来

**Comment by Callmebosswang** [comment]
@ome450901

**Comment by Callmebosswang** [comment]
请问我所述的问题在新版中得到解决了吗?

**Comment by wyy0567** [comment]
新版本还存在设置star数无效的情况

**Comment by ome450901** [comment]
Hello @Callmebosswang ,
目前測試上是沒有問題的哦！
若你在新的版本還是有碰到這個bug，麻煩提供一下你的佈局以及操作步驟供參考
謝謝！

**Comment by ome450901** [comment]
Hello @wyy0567 ,
可否提供你的操作步驟讓我參考一下呢？

**Comment by HLFGithub** [comment]
兄弟：
ScaleRatingBar fillRatingBar方法实现有问题。
比如我在一个列表上展示ScaleRatingBar

**Comment by ome450901** [comment]
Hello @HLFGithub ,
是否可以描述得更詳細一點呢？謝謝！

**Comment by lmqwudi** [comment]
我也碰到了，star有时候消失的bug

**Comment by ome450901** [comment]
Hello @lmqwudi ,
可否貼上你的實作方法供參考呢？
謝謝

**Comment by kangkangding** [comment]
我刚开始也不出现，去掉app:srb_starPadding="15dp" 这句就出现了

**Comment by wyy0567** [comment]
@kangkangding  出现了bug还是出现了星星

**Comment by wyy0567** [comment]
@ome450901 是在listview 中复用的情况下。一定概率出现星星消失不显示的情况

**Comment by kangkangding** [comment]
额，就是星星可以正常显示！没有遇到bug！

**Comment by ome450901** [comment]
@wyy0567 可否提供您實作的方式讓我參考一下呢，謝謝！
@kangkangding 感謝回覆！

**Comment by kangkangding** [comment]
<com.willy.ratingbar.ScaleRatingBar
                    xmlns:app="http://schemas.android.com/apk/res-auto"
                    android:id="@+id/simpleRatingBar"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    app:srb_numStars="5"
                    app:srb_rating="3"
                    app:srb_starWidth="15dp"
                    app:srb_starHeight="15dp"
                    app:srb_stepSize="0.5"
                    app:srb_isIndicator="true"
                    app:srb_clickable="true"
                    app:srb_scrollable="true"
                    app:srb_clearRatingEnabled="true"
                    app:srb_drawableEmpty="@mipmap/icon_star_gray"
                    app:srb_drawableFilled="@mipmap/icon_star_yellow"
                    >
这样就可以正常显示，只是去掉了app:srb_starPadding="15dp"，和替换了一下星星图片

**Comment by wyy0567** [comment]
@ome450901 <com.willy.ratingbar.BaseRatingBar
            android:id="@+id/rat_reco"
            app:srb_numStars="5"
            app:srb_clickable="false"
            app:srb_starPadding="10dp"
            app:srb_drawableEmpty="@mipmap/score_empt"
            app:srb_drawableFilled="@mipmap/score_o"
            android:layout_centerVertical="true"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginLeft="108dp" />属性没有写全的原因吗，我只是设置了部分

**Comment by ome450901** [comment]
Hello @wyy0567  @kangkangding ,
我重現問題了，這禮拜會試著解決，謝謝你們的幫忙！
