### ISSUE TITLE
java.lang.NumberFormatException: For input string: "0,57"

### ISSUE THREAD

**Issue by Sirelon** [ome450901/SimpleRatingBar#26]
at com.willy.ratingbar.BaseRatingBar.calculateRating(BaseRatingBar.java:318)

Hello. 
Noticed that crash in the locale, where separator in decimal is comma.  
I will prepare pull request for fix it. Thanks.

**Comment by ome450901** [comment]
Hello @Sirelon ,
I really don't know that separator in decimal is different in other country.
Thanks for your help!
