### ISSUE TITLE
不支持浮点数评分

### ISSUE THREAD

**Issue by walorwang** [ome450901/SimpleRatingBar#3]
不支持浮点数Float评分

**Comment by ome450901** [comment]
Thanks for your comment, I will put this feature in my todo list.

**Comment by zhangruize** [comment]
this also means you needs find a way to fill only a part of star image. good challenge

**Comment by ome450901** [comment]
Hello @zhangruize @walorwang,
I have found a way to fill only a part of star image,
and this feature will be added into next release.
you can checkout my implementation in `develop` branch first if you are interested!
Thanks!
