### ISSUE TITLE
Rating Bar Inside RecyclerView

### ISSUE THREAD

**Issue by iffanmajid** [ome450901/SimpleRatingBar#30]
I implement this rating as items inside recyclerview, but only last item received the value from array. have you ever tried it?

**Comment by abhilucks93** [comment]
Same issue here. Found any solution ?

**Comment by iffanmajid** [comment]
I have not successfully implemented this library as recyclerview items, so for now I change to this https://github.com/techery/ProperRatingBar @abhilucks93

**Comment by ome450901** [comment]
Hello @iffanmajid @abhilucks93 , 
I'll try to figure out this problem in this week, thanks you guys!

**Comment by ome450901** [comment]
Hello @iffanmajid , 
Do you mean your OnRatingChangeListener not working?
If so , my RecyclerView works fine. 

Could you put some of your implementation for me? 
Thanks again!

**Comment by 1277379283** [comment]
您好，本人非常喜欢您能把这个控件分享出来，这个问题我也遇到过了RecyleView，应该所有星星都有显示，但只显示了 最后一排的星星 。求解决

代码如下：
![qq 20171010173100](https://user-images.githubusercontent.com/13748217/31379461-e5ac7044-ade0-11e7-9b08-a8421739f81c.png)

效果如下：
![qq 20171010173024](https://user-images.githubusercontent.com/13748217/31379479-f3af9266-ade0-11e7-8285-b96a1b0d13d5.png)

**Comment by vickyramachandra** [comment]
Any update on this @ome450901 ?

**Comment by ome450901** [comment]
Hi guys, I have found the problem and trying to repair it.
Sorry I don't have much time to coding. (because my military service orz)
I'll fix this issue in next release ASAP, thank you all for the help.

**Comment by 1277379283** [comment]
ok，Thanks a lot brother！！！

**Comment by vickyramachandra** [comment]
Awesome .. Thanks :D
