### ISSUE TITLE
多个SimpleRatingBar问题

### ISSUE THREAD

**Issue by ITDreamSKY** [ome450901/SimpleRatingBar#32]
多个SimpleRatingBar同时使用，rating都设置满的，但是只有最后一个显示是对的，前面的显示都是空的，但rating值是对的

**Comment by ITDreamSKY** [comment]
ScaleRatingBar

**Comment by ITDreamSKY** [comment]
@ome450901

**Comment by ome450901** [comment]
Hi @ITDreamSKY , 
這個 issue 和 #30 是一樣的哦！ 
我已經正在處理了，謝謝！
