### ISSUE TITLE
View state such as rating is not restored from instance state

### ISSUE THREAD

**Issue by harshsharma94** [ome450901/SimpleRatingBar#35]
When activity/fragment is recreated, savedInstanceState is not restored for RatingBar.
Cause: Need to save rating state in parcel
How to reproduce: Turn on the flag, "Don't keep activities" in Developer Options.
And revisit sample Activity after setting rating.

I do have a PR which solves this issue.
Can you have a look ?

**Comment by ome450901** [comment]
Hello @harshsharma94 , 
Thanks for your help!! 
but I don't see any PR, could you send it again?
Thanks!

**Comment by harshsharma94** [comment]
PR created.

**Comment by ome450901** [comment]
Hello, 
I have accepted the PR, 
Thanks again for your help!
