### ISSUE TITLE
Incorrect View state when scrolling fast

### ISSUE THREAD

**Issue by harshsharma94** [ome450901/SimpleRatingBar#38]
RatingBar does not show correct state when moving over the layout quickly.

![Bug1](https://i.imgur.com/VVjCwSU.gif)

Also while hovering over the layout, if we drag the touch down and then move, it still responds to touch event.

![Bug2](https://i.imgur.com/lQC1a41.gif)

Also, there is no option to disable the scrolling behaviour and just retain the click behaviour.

**Comment by ome450901** [comment]
Thanks for your response!
I'll try to find out the bug and implement the feature of disable scrolling behavior.

The second issue, I think that is a appropriate behavior (android original RatingBar has same behavior), so I'll keep this behavior for now.

**Comment by ome450901** [comment]
I've fix this issue, thanks for your help!
