### ISSUE TITLE
How to change star width in code,not in xml?

### ISSUE THREAD

**Issue by treanow** [ome450901/SimpleRatingBar#44]
app:srb_starWidth="30dp"
app:srb_starHeight="30dp"

i have some different size , sometimes need app:srb_starWidth="30dp",but sometimes need app:srb_starWidth="20dp",
but i have not found method in code?
![default](https://user-images.githubusercontent.com/13456586/34510598-368b1e2e-f090-11e7-8847-14e71580dcc5.png)

**Comment by treanow** [comment]
原来是台湾同胞,哈哈,我就是想自定义一个View 包含了你这个控件,不同的尺寸,想动态设置星星的宽度,但是现在是不支持代码动态设置宽度吗?

**Comment by ome450901** [comment]
Hello @treanow ,
目前沒有加上這個API , 我之後會找時間加上
謝謝你的回覆！
