### ISSUE TITLE
How to know rating view is clicking ?

### ISSUE THREAD

**Issue by ismailtosun** [ome450901/SimpleRatingBar#47]
In recylerview adapter 

```
ratingBar.setOnRatingChangeListener(new BaseRatingBar.OnRatingChangeListener() {
    @Override
        public void onRatingChange(BaseRatingBar ratingBar, int rating) {
            Log.e(TAG, "onRatingChange: " + rating);
             holder.ratingView.setRate(4);
    }
});
```

in this rate action I want to set new rate holder.ratingView.setRate(4);
but it's show rating value ? why ?

**Comment by ome450901** [comment]
Hello @ismailtosun , 

I'm not sure what's your problem, 
did you mean the code `holder.ratingView.setRate(4);` doesn't work?

**Comment by ismailtosun** [comment]
no,I mean when I click the rateview, I want to show an alert dialog.And don't want to let rate.
