### ISSUE TITLE
点击在两个星星中间的空白位置，会返回0

### ISSUE THREAD

**Issue by arthur20150522** [ome450901/SimpleRatingBar#53]
1、点击在两个星星中间的空白位置，概率会返回0
2、能否加个功能，就是监听只监听最终结果，目前实现的只能点击回调，或者滑动一直回调两种

Thanks♪(･ω･)ﾉ

**Comment by ome450901** [comment]
Hello @arthur20150522 , 

謝謝你回報這個問題，我會再找時間盡快修復！
另外能否麻煩你再詳細描述一下第二個功能或是給個例子呢，我沒有很懂這是什麼樣的功能

謝謝！
