### ISSUE TITLE
RatingBarUtils.calculateRating泰文环境下崩溃。

### ISSUE THREAD

**Issue by OrientalJew** [ome450901/SimpleRatingBar#56]
进行该操作：
Float.parseFloat(decimalFormat.format((eventX - partialView.getLeft()) / partialView.getWidth()))
报java.lang.NumberFormatException

DecimalFormatSymbols symbols = new DecimalFormatSymbols(); 
建议改为：
DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.ENGLISH);

不同地区可能有不同的数字格式，比如泰文环境下，๐.๑๔表示0.14

**Comment by ome450901** [comment]
@OrientalJew 
Thank you, I'll fix this bug in next release.

**Comment by ome450901** [comment]
Hello @ayham95 
Sorry that I've been busy these days, I have already release the new version.
thank you!
