### ISSUE TITLE
Scroll rating bar

### ISSUE THREAD

**Issue by Swwwifty** [ome450901/SimpleRatingBar#60]
I have a problem with scroll in recyclerview.

If I start scroll event from ratingbar then fires *OnRatingChangeListener*
Is it possible to set rating only on click event, but not scroll? Thanks!

**Comment by ome450901** [comment]
Hello @Swwwifty , 

You can try to set the following value to disable scroll event:
`app:srb_scrollable="false"` or `ratingbar.setScrollable(false);`

Hope this works for you.

**Comment by Swwwifty** [comment]
Thanks for the answer. It works, but it's partial solution. I want to save scroll works, but handle only clicks.
Now I think that I can handle with it with different *onTouch motion actions*
