### ISSUE TITLE
match_parent not work

### ISSUE THREAD

**Issue by LSDsl** [ome450901/SimpleRatingBar#62]
When set layout_width to match_parent stars not use all width. Expectation - it add spaces between stars to use all width. Is it possible?

**Comment by ome450901** [comment]
Hi @LSDsl,

Thanks for issue this feature, I'll try it recently.

**Comment by alonfi** [comment]
Hi @ome450901, did you get a chance to look into the match_parent issue?
Setting a fixed srb_starPadding causes the stars to be cut off if the screen is not wide enough to contain the total width of the stars and their set padding. It would be convenient if the padding would be dynamic and change according to the parent's width.

In addition, it would be nice if different starPadding values could be set on different sides of the star, for example add padding horizontally between the stars, but don't add padding vertically above and below the stars.

**Comment by ome450901** [comment]
Hi @alonfi 
Sorry I haven't started working on it yet,  it's quite busy at the moment.
Thanks for the suggestion though, I'll try to have a look over the weekend.

**Comment by ome450901** [comment]
[Fixed commit](https://github.com/ome450901/SimpleRatingBar/commit/42957482f366b583ca446f83867289cdb05b4834)
