### ISSUE TITLE
禁止星星转动的动画

### ISSUE THREAD

**Issue by vonions** [ome450901/SimpleRatingBar#65]

**Comment by ome450901** [comment]
Hello @vonions,
請問是希望可以禁止星星轉動嗎？

**Comment by vonions** [comment]
是的，怎么禁止星星转动

**Comment by ome450901** [comment]
BaseRatingBar 就是沒有任何動畫的，請問你目前是使用這個嗎？

**Comment by vonions** [comment]
我用的  RotationRatingBar， 我替换成BaseRatingBar就好了，谢谢 ！
