### ISSUE TITLE
setOnRatingChangeListener infinate loop

### ISSUE THREAD

**Issue by ShahabGT** [ome450901/SimpleRatingBar#68]
Hello, there is a big flow with this library (at least i think so).
my app has a rating system that you can rate a shop from 1 to 5 stars.
the problem is on setOnRatingChangeListener i want to send the selected rate to a server and refresh the rating bar with the received data from the server. so when it happens the setOnRatingChangeListener will trigger and it becomes an infinite loop.
ps. in android RattingBar in setOnRatingBarChangeListener there is a boolean value called fromUser which will determine a user selected that value or it's been set from code. THIS IS what your library missing.

**Comment by ome450901** [comment]
Hi @ShahabGT, 
Thanks for raising the issue, I'll put this into TODO list.

**Comment by jcholin** [comment]
Hi @ome450901,
Any hope to have a new release with this fix? thx

**Comment by ome450901** [comment]
Hi @jcholin , 
Just released 1.4.3 to fix this issue, thanks.
