### ISSUE TITLE
《请问为什么没有任何效果》QQ478104175

### ISSUE THREAD

**Issue by xuxinjiang** [ome450901/SimpleRatingBar#70]
<com.willy.ratingbar.BaseRatingBar
                            android:id="@+id/baseRatingBar1"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            app:srb_clearRatingEnabled="true"
                            app:srb_clickable="true"
                            app:srb_drawableEmpty="@drawable/xing_l"
                            app:srb_drawableFilled="@drawable/xing_x"
                            app:srb_isIndicator="false"
                            app:srb_numStars="5"
                            app:srb_rating="0"
                            app:srb_scrollable="true"
                            app:srb_starHeight="20dp"
                            app:srb_starPadding="5dp"
                            app:srb_starWidth="20dp"
                            app:srb_stepSize="0.5" />

**Comment by xuxinjiang** [comment]
我改的图片根本设置不进去？

**Comment by ome450901** [comment]
Hi @xuxinjiang , 
我這邊測試是正常的，能請你提供你使用的圖片嗎
