### ISSUE TITLE
如果在recyclerview中使用，notifydatasetchanged之后，已选选项会消失

### ISSUE THREAD

**Issue by xxh3145987** [ome450901/SimpleRatingBar#78]

**Comment by ome450901** [comment]
Hello @xxh3145987 
不確定你的使用情境，不過通常你需要有一個 List 去記錄你的星星個數
因為 Recyclerview 會把已經看不見的 View recycle 回來重新使用
所以你需要在綁定 View 時把值設定給 RatingBar ，這樣星星的狀態才不會消失
