### ISSUE TITLE
Not able to disable change rating 

### ISSUE THREAD

**Issue by ankathiriya** [ome450901/SimpleRatingBar#81]
I have set this layout : 
 <com.willy.ratingbar.ScaleRatingBar
            android:id="@+id/ratingBar"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:srb_clearRatingEnabled="false"
            app:srb_clickable="false"
            app:srb_drawableEmpty="@drawable/ic_star_empty"
            app:srb_drawableFilled="@drawable/ic_star_fill"
            app:srb_isIndicator="false"
            app:srb_minimumStars="0"
            app:srb_numStars="5"
            app:srb_rating="0"
            app:srb_scrollable="true"
            app:srb_starHeight="20dp"
            app:srb_starPadding="0dp"
            app:srb_starWidth="20dp" />

but then also i can change rating

**Comment by ome450901** [comment]
@ankathiriya hello, you need to set the "app:srb_isIndicator" to true.
